In this section, we review the $\meta{d'}$ model, focusing on its generative mechanism for confidence ratings and the unique parameterization of the model used in the `hmetad` package.

## Data
The $\meta{d'}$ model can be used to describe data from binary choice tasks with ordinal-valued confidence ratings. That is, given a stimulus $S \in \{0, 1\}$, the participant is asked to make a response $R \in \{0, 1\}$ along with a confidence rating $C \in \{1, \ldots, K\}$ (where $K$ is the maximum confidence rating), such that the participant's decision is correct if $R = S$. For instance, participants might be asked to judge whether a stimulus is old (i.e., presented in a prior study phase) or new, determine whether a random dot motion stimulus is moving left or right, or decide which of two food items contains more calories. Along with the primary decision, participants are asked to rate their confidence in their decision on an ordinal scale indicating whether their decision was a guess, made with high confidence, or somewhere in between.^[Note that the lower bound on this scale represents guesses, not decisions which the participant is confident are incorrect. Although such changes of mind are of interest to metacognition research, they are incompatible with the $\meta{d'}$ model and tend to be very infrequent in controlled laboratory tasks.] Following @clarke1959, we refer to the primary decision as the \emph{type 1} task and the task of rating confidence as the \emph{type 2} task. 

While it is designed for experimental paradigms with separate type 1 and type 2 decisions, the $\meta{d'}$ model is also compatible with paradigms in which the participants make a joint type 1/type 2 response with endpoints representing a confident decision in either of the two type 1 responses and with the center representing low confidence^[Because it is designed for tasks in which the type 1 task is forced-choice, the $\meta{d'}$ model can only be used when the joint response has an even number of values.] ($J \in \{1, \ldots, 2K\}$, see Figure \ref{fig:measurement}). This design is often preferable because it takes less time than separate responses and it better controls for reaction times. One can convert between the separate and joint responses using the equations below, implemented as the functions `type1_response`, `type2_response`, and `joint_response` in the `hmetad` package:

\begin{align*}
    R &= \llbracket J > K \rrbracket \\
    C &= \begin{cases}
       J-K & \textrm{if } R=1 \\
       K+1-J & \textrm{if } R=0 \\
    \end{cases} \\
    J &= \begin{cases}
       K+C & \textrm{if } R=1 \\
       K+1-C & \textrm{if } R=0 \\
    \end{cases}
\end{align*}



\begin{figure}
    \centering
    \caption{TODO: demonstration of different kinds of metacognition tasks}
    \label{fig:measurement}
\end{figure}


## Generative model
Given the design above, the $\meta{d'}$ model aims to explain the distribution of type 1 and type 2 responses. Early descriptions of the model stressed that it was not intended to be a generative model; initially, it was simply meant to describe (a) the relation between type 1 responses and the stimulus, and (b) the relation between type 2 responses and the accuracy of the type 1 responses. However, over time this characterization has shifted to an understanding that the $\meta{d'}$ model is sensitive to a number of generative assumptions, indicating that it is not in fact a theory-free model [@guggenmos2021; @rausch2023]. Keeping this in mind, we next overview the generative process underlying the $\meta{d'}$ model, identifying relevant assumptions along the way.
 
### Type 1 responses
As the $\meta{d'}$ model is an extension of Signal Detection Theory (SDT), its model for type 1 responses is simply the equal variance signal detection model [@green1966; @clarke1959]. Given the stimulus $S$, equal variance SDT assumes that the observer is presented with a noisy signal $x_1 \sim \mathcal{D}_S(d')$ following a distribution $\mathcal{D}$ parameterized by the observer's sensitivity to the stimulus $d'$. Although other options are available, it is common to assume that $\mathcal{D}$ is a normal distribution with unit variance, such that:
\begin{align*}
    \mathcal{D}_0(d') &= \mathcal{N}\left(-\frac{d'}{2}, 1\right) \\
    \mathcal{D}_1(d') &= \mathcal{N}\left(\frac{d'}{2}, 1\right)
\end{align*}
In the type 1 task, the observer is meant to determine the underlying value of $S$ on the basis of its noisy signal $x_1$. To make a response, then, it is assumed that the observer thresholds the signal $x_1$ to a criterion $c$:
\begin{align*}
    R = \llbracket x_1 > c\rrbracket
\end{align*}
Instead of modeling $x_1$ directly, it is more efficient to marginalize over it to compute the implied probability distribution over type 1 responses. Where $F_{\mathcal{D}}$ is the cumulative distribution function of $\mathcal{D}$, this process entails that the observer makes type 1 responses with probability:
\begin{align*}
    P(R=r \;\vert\; S=s) = \begin{cases}
        1 - F_{\mathcal{D}_{s}(d')}(c) & \textrm{if }r=1 \\
        F_{\mathcal{D}_{s}(d')}(c)  & \textrm{if }r=0
    \end{cases}
\end{align*}
For example, the observer's type 1 hit rate is $P(R=1 \;\vert\; S=1) = 1 - F_{\mathcal{D}_{1}(d')}(c)$ and their type 1 false alarm rate is $P(R=1 \;\vert\; S=0) = 1 - F_{\mathcal{D}_{0}(d')}(c)$.


### Type 2 responses
In the type 2 task, the observer is asked to determine their confidence in their type 1 response. A crucial aspect of the $\meta{d'}$ model is that it does not assume that the observer has access to the same information for the type 1 and type 2 tasks: it could be the case that the observer gained or lost information about the stimulus after the type 1 response was made. As a result, the $\meta{d'}$ model assumes that the observer makes type 2 responses using a separate decision variable following a truncated distribution (with bounds indicated using superscripts):
\begin{align*}
    x_2 \sim \begin{cases}
        \mathcal{D}_S^{(-\infty, \meta{c}]}(\meta{d'}) & \textrm{if } R=0 \\
        \mathcal{D}_S^{[\meta{c}, \infty)}(\meta{d'}) & \textrm{if } R=1
\end{cases}
\end{align*}
This type 2 decision variable has two important characteristics. First, parameters used to generate type 2 responses are named with the prefix ``meta-'' to distinguish them from parameters used to generate the type 1 responses. Second, $x_2$ is upper-bounded by $\meta{c}$ when $R=0$ and lower-bounded by $\meta{c}$ when $R=1$ so that $x_2$ cannot contradict the type 1 response implied by $x_1$ (i.e., the $\meta{d'}$ model does not allow for changes of mind). Then, to determine the confidence level $C \in \{ 1 \ldots K\}$, the observer rates confidence using a set of $K-1$ ordered confidence criteria, $\metabf{c_2^R}$:
\begin{align*}
    C &= \begin{cases}
    1+\Sigma_{k=1}^{K-1}[x_2 < \meta{c}_{2,k}^0] & \textrm{if } R=0 \\
    1+\Sigma_{k=1}^{K-1} [x_2 > \meta{c}_{2,k}^1] & \textrm{if } R=1
    \end{cases}
\end{align*}
As with the type 1 response, it is most efficient to marginalize over $x_2$ to compute the probability of a type 2 response given the stimulus and type 1 response:
\begin{align*}
    P(C=c \;\vert\; S=s,R=r) &= \begin{cases}
    \frac{F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c}\right) -
    F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c_{2,1}^0}\right)}
    {F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c}\right)}
    & \textrm{if } r=0, c=1 \\
    \frac{F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c_{2,k}^0}\right) -
    F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c_{2,k+1}^0}\right)}
    {F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c}\right)}
    & \textrm{if } r=0, 1 \le c \le K \\
    \frac{F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c_{2,K}^0}\right)}
    {F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c}\right)}
    & \textrm{if } r=0, c = K \\
    \frac{F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c_{2,1}^1}\right) -
    F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c}\right)}
    {1 - F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c}\right)}
    & \textrm{if } r=1, c=1 \\
    \frac{F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c_{2,k+1}^1}\right) -
    F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c_{2,k}^}1\right)}
    {1 - F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c}\right)}
    & \textrm{if } r=1, 1 \le c \le K \\
    \frac{1 - F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c_{2,K}^1}\right)}
    {1 - F_{\mathcal{D}_s(\meta{d'})}\left(\meta{c}\right)}
    & \textrm{if } r=1, c = K
    \end{cases}
\end{align*}
In each of these equations, the numerator is the probability that $x_2$ lies between the thresholds for confidence level $c$, and the denominator is a normalization term to deal with the fact that $x_2$ is truncated above or below by $\meta{c}$.

### Joint likelihood
The $\meta{d'}$ model aims to explain the joint distribution of type 1 and type 2 responses, which can conveniently be factored into a product of the type 1 and type 2 response probabilities:
\begin{align*}
    P(R=r, C=c \;\vert\; S=s) = P(R=r \;\vert\; S=s) \; P(C=c \;\vert\; S=s, R=r) 
\end{align*}
Note that because this distribution is conditional on the stimulus $S$, the $\meta{d'}$ model does not model the base rate $P(S=s)$. We consider two specifications of the model likelihood. When trial-level effects are of interest, one can fit the $\meta{d'}$ model to individual trials using a categorical distribution. Where $\mathcal{L}$ is the likelihood, $\bm{\theta} = \{d', c, \meta{d'}, \meta{c}, \metabf{c_2^0}, \metabf{c_2^1}\}$, and $\bm{s}$, $\bm{r}$, and $\bm{c}$ vectors of observed stimuli, type 1 responses, and type 2 responses:
\begin{align*}
    \mathcal{L}(\bm{\theta} \;\vert\; S=\bm{s},R=\bm{r},C=\bm{c}) &= \prod_{n=1}^N P(R=r_n, C=c_n \;\vert\; S=s_n)
\end{align*}
However, in this formulation the number of times each conditional probability is computed is proportional to the number of trials with the same stimulus, type 1 response, and type 2 response. As noted by @maniscalco2014, it is often more efficient to use a multinomial likelihood over the aggregated data instead. Where $N_{s,r,c}$ is the number of trials with stimulus $S=s$, type 1 response $R=r$, and type 2 response $C=c$:
\begin{align*}
    \mathcal{L}(\bm{\theta} \;\vert\; \bm{N}) &\propto \prod_{s,r,c} P(R=r, C=c \;\vert\; S=s)^{N_{s,r,c}}
\end{align*}
For numerical stability, the `hmetad` package evaluates the model likelihood on the logarithmic scale. For a detailed derivation of the log likelihood used in the model fitting code, see @apx-ll.



## Fixing the type 1 criterion for type 2 responses
In principle, one could treat $\meta{c}$ as a free parameter reflecting the type 1 criterion of the generative model for type 2 responses.^[I originally thought that the model would be unidentifiable with $\meta{c}$ as a free parameter, but it seems to actually work perfectly fine! It might make interpretation more difficult, but perhaps this is also a feature to include in the package?] But to ease comparisons between $\meta{d'}$ and $d'$, in addition to comparisons across participants or experiments, it is instead customary to fix $\meta{c}$ to be similar in some respect to the type 1 criterion ($c$). @maniscalco2014 advocate for two options in particular (Figure \ref{fig:metac}).

In the [absolute]{.smallcaps} model, $\meta{c}$ is simply fixed to the type 1 criterion (i.e., $\meta{c} = c$). This is the parameterization used in the Hmeta-d package and is the default in the `hmetad` package [@fleming2017]. In the [relative]{.smallcaps} model, $\meta{c}$ is fixed to be equal to the type 1 criterion relative to the sensitivity (i.e., $\frac{\meta{c}}{\meta{d'}} = \frac{c}{d'}$). This is achieved by setting $\meta{c} = \frac{\meta{d'}}{d'}c$. This is the parameterization used by @maniscalco2014 and can be used in the `hmetad` package using the option `metac_absolute=FALSE`. Critically, @rausch2023 demonstrated that the choice between these two models is not arbitrary, as fitting data generated from the opposite generative model induces small but significant spurious dependencies of $\meta{d'}$ on other model parameters.

::: {#fig-metac}

Two options for fixing the type 1 criterion for generating type 2 responses.
:::

## Parameterization in the `hmetad` package
As described above, the likelihood of the $\meta{d'}$ model is defined in terms of is parameters, $\bm{\theta} = \{d', c, \meta{d'}, \meta{c}, \metabf{c_2^0}, \metabf{c_2^1}\}$. To enable efficient model fitting, the `hmetad` package uses an alternative parameterization that derives these parameters from transformed variables.

First, instead of fitting $\meta{d'}$ directly, the `hmetad` package instead models the $M$-ratio, $M = \frac{\meta{d'}}{d'}$. To ensure that $0 \le M \le \infty$, the $M$-ratio is modeled with a logarithmic link function. In this parameterization, one can compute $\meta{d'}$ using the transformation $\meta{d'} = Md'$.

Second, in the original parameterization, the type 2 criteria are ordinally constrained. Specifically, for $R=0$, $\metabf{c_2^0}$ is constrained to be decreasing and below $\meta{c}$ and for $R=1$, $\metabf{c_2^1}$ is constrained to be decreasing and above $\meta{c}$:
$$\meta{c_{2,K}^0} \le \ldots \le \meta{c_{2,1}^0} \le\meta{c} \le \meta{c_{2,1}^1} \le \ldots \le \meta{c_{2,K}^1}$$
Previous implementations of the model either used constrained optimization [@maniscalco2014] or sorted the type 2 criteria [@fleming2017] to meet this constraint. As a more flexible alternative, the `hmetad` package instead uses the positive ordered transform to model the \emph{differences} between successive type 2 criteria. Where $K$ is the number of confidence levels, $K-1$ is the number of confidence criteria per response, and $\delta\meta{c_{2,k}^0}$ and $\delta\meta{c_{2,k}^1}$ are the distances between type 2 criteria for $R=0$ and $R=1$:
\begin{align*}
    \delta\meta{c_{2,k}^0} = \begin{cases}
        \meta{c} - \meta{c_{2,1}^0} & \textrm{if } k = 1 \\
        \meta{c_{2,k-1}^0}  - \meta{c_{2,k}^0} & \textrm{if } 2 \le k \le K-1
    \end{cases} \\
    \delta\meta{c_{2,k}^1} = \begin{cases}
        \meta{c_{2,1}^1} - \meta{c} & \textrm{if } k = 1 \\
        \meta{c_{2,k}^1} - \meta{c_{2,k-1}^1} & \textrm{if } 2 \le k \le K-1
    \end{cases}
\end{align*}
Under this parameterization, the actual type 2 criteria are computed using the inverse transform:
\begin{align*}
    \metabf{c_2^0} &= \meta{c} - \textrm{cumulative\_sum}\!\left(e^{\delta\meta{c_2^0}}\right) \\
    \metabf{c_2^1} &= \meta{c} + \textrm{cumulative\_sum}\!\left(e^{\delta\meta{c_2^1}}\right)
\end{align*}
As with the $M$-ratio, the distances $\delta\meta{c_{2,k}^0}$ and $\delta\meta{c_{2,k}^1}$ are modeled with a logarithmic link function to ensure that they are positive.


### Including predictors
The primary benefit of the `hmetad` package is that it specifies the $\meta{d'}$ model as a generalized linear model, allowing users to specify model parameters as a linear function of observed variables. For instance, where $\bm{X_\varphi}$ and $\beta_\varphi$ are the design matrix and coefficient vector for each parameter $\varphi$, the `hmetad` package uses the linear model:
\begin{align*}
    \log(M) &= \bm{X_M}\beta_M \\
    d' &= \bm{X_{d'}}\beta_{d'} \\
    c &= \bm{X_c}\beta_c \\
    \log(\delta\meta{c_{2,k}^0}) &= \bm{X_{\delta\metabf{c_{2,k}^0}}}\beta_{\delta\meta{c_{2,k}^0}} \\
    \log(\delta\meta{c_{2,k}^1}) &= \bm{X_{\delta\metabf{c_{2,k}^1}}}\beta_{\delta\meta{c_{2,k}^1}}
\end{align*}
Importantly, the `hmetad` package allows for the design matrices to differ for each model parameter. As with any other `brms` family, it is also possible to include multilevel (or hierarchical) structure [@buerkner2018]. Where $\bm{Z_\varphi}$ and $\gamma_\varphi$ are the group-level design matrix and coefficient vector for each parameter $\varphi$:
\begin{align*}
    \log(M) &= \bm{X_M}\beta_M \;+\; \bm{Z_M}\gamma_M \\
    d' &= \bm{X_{d'}}\beta_{d'} \;+\; \bm{Z_{d'}}\gamma_{d'} \\
    c &= \bm{X_c}\beta_c \;+\; \bm{Z_c}\gamma_c \\
    \log(\delta\meta{c_{2,k}^0}) &= \bm{X_{\delta\metabf{c_{2,k}^0}}}\beta_{\delta\meta{c_{2,k}^0}} \;+\; \bm{Z_{\delta\metabf{c_{2,k}^0}}}\gamma_{\delta\meta{c_{2,k}^0}} \\
    \log(\delta\meta{c_{2,k}^1}) &= \bm{X_{\delta\metabf{c_{2,k}^1}}}\beta_{\delta\meta{c_{2,k}^1}} \;+\; \bm{Z_{\delta\metabf{c_{2,k}^1}}}\gamma_{\delta\meta{c_{2,k}^1}}
\end{align*}
Although a full description of all of the different kinds of predictors allowed in `brms` is outside the scope of this article, `brms` also allows for non-linear terms, monotonic predictors, autocorrelation terms, and predictors with measurement error [@buerkner2017; @buerkner2018; @buerkner2020].
